# Generated by Django 5.2.4 on 2025-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
