# Generated by Django 5.2.2 on 2025-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(default='news', max_length=100),
        ),
    ]
